M48
; DRILL file {KiCad (6.0.5)} date Fri May 16 22:36:26 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-16T22:36:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X218.491Y-198.653
T2
X135.738Y-92.202
X136.195Y-168.326
X288.341Y-213.258
X288.392Y-92.329
T0
M30
